#!/usr/bin/env python3
"""Generate kernel/arch/x86/isr.S (interrupt entry stubs).

Run from the repository root:  python3 tools/gen_isr.py
"""
import os

ERR_CODE_VECTORS = {8, 10, 11, 12, 13, 14, 17, 21}

HEADER = """/*
 * Interrupt entry stubs.
 *
 * The CPU pushes an error code for some exceptions and not for others, so the
 * stubs that do not get one push a dummy zero.  Every stub then pushes its
 * vector number and falls into the common trampoline, which saves the full
 * register frame and calls isr_dispatch().
 *
 * This file is generated by tools/gen_isr.py -- edit that, not this.
 */
.section .text
"""

COMMON = """isr_common:
    pusha                           /* edi esi ebp esp ebx edx ecx eax */
    movl    %ds, %eax
    pushl   %eax                    /* save the data segment */

    movw    $0x10, %ax              /* switch to kernel data segments */
    movw    %ax, %ds
    movw    %ax, %es
    movw    %ax, %fs
    movw    %ax, %gs

    pushl   %esp                    /* struct registers * */
    call    isr_dispatch
    addl    $4, %esp

    popl    %eax                    /* restore the caller's segments */
    movw    %ax, %ds
    movw    %ax, %es
    movw    %ax, %fs
    movw    %ax, %gs

    popa
    addl    $8, %esp                /* drop int_no and err_code */
    iret

.section .data
.global isr_stub_table
.align 4
isr_stub_table:
"""


def generate():
    out = [HEADER]
    for i in range(32):
        out.append(".global isr%d\nisr%d:\n    cli\n" % (i, i))
        if i not in ERR_CODE_VECTORS:
            out.append("    pushl $0\n")
        out.append("    pushl $%d\n    jmp isr_common\n\n" % i)
    for i in range(16):
        out.append(".global irq%d\nirq%d:\n    cli\n    pushl $0\n"
                   "    pushl $%d\n    jmp isr_common\n\n" % (i, i, 32 + i))
    out.append(".global isr128\nisr128:\n    cli\n    pushl $0\n"
               "    pushl $128\n    jmp isr_common\n\n")
    out.append(COMMON)
    for i in range(32):
        out.append("    .long isr%d\n" % i)
    for i in range(16):
        out.append("    .long irq%d\n" % i)
    out.append("    .long isr128\n")
    return "".join(out)


if __name__ == "__main__":
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "..", "kernel", "arch", "x86", "isr.S")
    with open(os.path.normpath(path), "w") as fh:
        fh.write(generate())
    print("wrote", os.path.normpath(path))
